Repository OpenBioSim/biosimspace, pull requests merged in 2023-06, with the labels that each got.

#79 Fix issue #78
  python/BioSimSpace/Sandpit/Exscientia/Process/_amber.py
  tests/Sandpit/Exscientia/Process/test_amber.py
  tests/Sandpit/Exscientia/output/amber_fep.out
Labels: bug, exscientia

#105 Fix issue #92
  python/BioSimSpace/Process/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_amber.py
Labels: bug

#106 Backport fix from PR #105
  python/BioSimSpace/Process/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_amber.py
Labels: bug

#109 Improve unit parsing using Sire unit grammar
  python/BioSimSpace/Notebook/_plot.py
  python/BioSimSpace/Process/_gromacs.py
  python/BioSimSpace/Sandpit/Exscientia/Notebook/_plot.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
  python/BioSimSpace/Sandpit/Exscientia/Types/_general_unit.py
  python/BioSimSpace/Sandpit/Exscientia/Types/_type.py
  python/BioSimSpace/Types/_general_unit.py
  python/BioSimSpace/Types/_type.py
  tests/Sandpit/Exscientia/Types/test_general_unit.py
  tests/Types/test_general_unit.py
Labels: enhancement, exscientia

#110 Expose Sire "make whole" functionality
  python/BioSimSpace/IO/_io.py
  python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py
  python/BioSimSpace/Process/_plumed.py
  python/BioSimSpace/Sandpit/Exscientia/IO/_io.py
  python/BioSimSpace/Sandpit/Exscientia/Metadynamics/CollectiveVariable/_funnel.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_plumed.py
  python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_system.py
  python/BioSimSpace/_SireWrappers/_system.py
Labels: bug, enhancement

#111 Fix issue #84
  python/BioSimSpace/Notebook/_plot.py
  python/BioSimSpace/Sandpit/Exscientia/Notebook/_plot.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_amber.py
  tests/Sandpit/Exscientia/output/amber_fep.out
Labels: bug, exscientia

#113 Correctly handle PLUMED version number
  python/BioSimSpace/Process/_plumed.py
  python/BioSimSpace/Sandpit/Exscientia/Process/_plumed.py
Labels: bug

#115 Fix issue #114
  python/BioSimSpace/Protocol/_steering.py
  python/BioSimSpace/Sandpit/Exscientia/Protocol/_metadynamics.py
  python/BioSimSpace/_Config/_gromacs.py
Labels: bug

#117 Fix issue #116
  recipes/biosimspace/template.yaml
Labels: bug

#119 Bugfix Somd Analysis
  python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
Labels: bug

#121 Add support for Sire as a trajectory backend
  python/BioSimSpace/Sandpit/Exscientia/Trajectory/_trajectory.py
  python/BioSimSpace/Trajectory/_trajectory.py
  tests/Sandpit/Exscientia/Trajectory/test_trajectory.py
  tests/Trajectory/test_trajectory.py
Labels: enhancement
