Repository OpenBioSim/biosimspace, pull requests merged in 2024-10, with the labels that each got.

#351 Backport fixes from PR #345 and #349
  python/BioSimSpace/Align/_merge.py
  python/BioSimSpace/Parameters/_Protocol/_openforcefield.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_openforcefield.py
Labels: bug

#352 Fix issue #330
  doc/source/tutorials/hydration_freenrg.rst
  doc/source/tutorials/images/ethane_methanol_mapping.png
  python/BioSimSpace/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Parameters/_Protocol/_openforcefield.py
  python/BioSimSpace/Process/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_openforcefield.py
  tests/Parameters/test_parameters.py
  tests/Sandpit/Exscientia/Parameters/test_parameters.py
Labels: bug

#353 Backport fixes from PR #352
  doc/source/tutorials/hydration_freenrg.rst
  doc/source/tutorials/images/ethane_methanol_mapping.png
  python/BioSimSpace/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Parameters/_Protocol/_openforcefield.py
  python/BioSimSpace/Process/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_openforcefield.py
  tests/Parameters/test_parameters.py
  tests/Sandpit/Exscientia/Parameters/test_parameters.py
Labels: bug

#327 Alchemical Transfer Method
  doc/source/api/index_Align.rst
  doc/source/api/index_FreeEnergy.rst
  doc/source/index.rst
  doc/source/tutorials/alchemical_transfer.rst
  doc/source/tutorials/images/alignment_visualisation.png
  doc/source/tutorials/images/pfep_thermodynamic_cycle.png
  doc/source/tutorials/images/tyk2_prepared.png
  doc/source/tutorials/index.rst
  doc/source/tutorials/protein_mutations.rst
  python/BioSimSpace/FreeEnergy/__init__.py
  python/BioSimSpace/FreeEnergy/_atm.py
  python/BioSimSpace/FreeEnergy/_ddg.py
  python/BioSimSpace/Process/_atm.py
  python/BioSimSpace/Process/_atm_utils.py
  python/BioSimSpace/Process/_openmm.py
  python/BioSimSpace/Protocol/__init__.py
  python/BioSimSpace/Protocol/_atm.py
  python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_system.py
  python/BioSimSpace/_SireWrappers/_system.py
  tests/FreeEnergy/test_atm.py
  tests/Process/test_atm.py
  tests/Protocol/test_atm.py
  tests/conftest.py
Labels: enhancement, exscientia

#356 Synchronise with Exscientia remote
  .github/workflows/Sandpit_exs.yml
  python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
  python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
  python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_molecule.py
  tests/Sandpit/Exscientia/Process/test_position_restraint.py
  tests/Sandpit/Exscientia/_SireWrappers/test_molecule.py
Labels: exscientia

#360 Improve robustness of restraint search and fix torsional force constant bug
  python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_restraint_search.py
  tests/Sandpit/Exscientia/FreeEnergy/test_restraint_search.py
Labels: bug

#361 Fix issue #347
  python/BioSimSpace/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Parameters/_parameters.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_parameters.py
  tests/Parameters/test_parameters.py
  tests/Sandpit/Exscientia/Parameters/test_parameters.py
Labels: bug

#362 Backport fixes from PR #360 and #361
  python/BioSimSpace/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Parameters/_parameters.py
  python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_restraint_search.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_Protocol/_amber.py
  python/BioSimSpace/Sandpit/Exscientia/Parameters/_parameters.py
  tests/Parameters/test_parameters.py
  tests/Sandpit/Exscientia/FreeEnergy/test_restraint_search.py
  tests/Sandpit/Exscientia/Parameters/test_parameters.py
Labels: bug
